# Generated by Django 4.2.3 on 2023-07-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('username', models.CharField(default='default', max_length=200)),
                ('password', models.CharField(default='default', max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
